export enum ChairDecision {
  APPROVED = 'APPROVED',
  CONDITIONALLY_APPROVED = 'CONDITIONALLY_APPROVED',
  REVISIONS_REQUIRED = 'REVISIONS_REQUIRED',
  REJECTED = 'REJECTED',
  RFDR = 'RFDR',
  RTIC = 'RTIC',
}
