export enum ApplicationType {
  NEW = 'NEW',
  AMENDMENT = 'AMENDMENT',
  RENEWAL = 'RENEWAL',
  PROGRESS_REPORT = 'PROGRESS_REPORT',
  AE_REPORT = 'AE_REPORT',
  SAE_REPORT = 'SAE_REPORT',
  PROTOCOL_DEVIATION = 'PROTOCOL_DEVIATION',
  CLOSURE = 'CLOSURE',
}
