export enum ResearchArea {
  CLINICAL_TRIAL = 'CLINICAL_TRIAL',
  PUBLIC_HEALTH = 'PUBLIC_HEALTH',
  EPIDEMIOLOGY = 'EPIDEMIOLOGY',
  SOCIAL_SCIENCES = 'SOCIAL_SCIENCES',
  BASIC_SCIENCE = 'BASIC_SCIENCE',
  COMMUNITY_HEALTH = 'COMMUNITY_HEALTH',
  NURSING_AND_MIDWIFERY = 'NURSING_AND_MIDWIFERY',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  ENVIRONMENTAL_HEALTH = 'ENVIRONMENTAL_HEALTH',
  OTHER = 'OTHER',
}
