export enum StudyDesign {
  RCT = 'RCT',
  NON_RANDOMIZED_CONTROLLED_TRIAL = 'NON_RANDOMIZED_CONTROLLED_TRIAL',
  COHORT_PROSPECTIVE = 'COHORT_PROSPECTIVE',
  COHORT_RETROSPECTIVE = 'COHORT_RETROSPECTIVE',
  CASE_CONTROL = 'CASE_CONTROL',
  CROSS_SECTIONAL = 'CROSS_SECTIONAL',
  CASE_SERIES = 'CASE_SERIES',
  QUALITATIVE_STUDY = 'QUALITATIVE_STUDY',
  SYSTEMATIC_REVIEW = 'SYSTEMATIC_REVIEW',
  MIXED_METHODS = 'MIXED_METHODS',
  OTHER = 'OTHER',
}
