export enum RoleName {
  APPLICANT = 'APPLICANT',
  REVIEWER = 'REVIEWER',
  IRB_ADMIN = 'IRB_ADMIN',
  RNEC_ADMIN = 'RNEC_ADMIN',
  FINANCE = 'FINANCE',
  CHAIRPERSON = 'CHAIRPERSON',
  SYS_ADMIN = 'SYS_ADMIN',
}
